### ISSUE TITLE
Examples: What Sanitizers Are in Scope

### ISSUE THREAD

**Issue by leeN** [SonarSource/mxss-cheatsheet#8]
Hi,

First of all, thanks for this resource! I have a bunch of other bypass payloads from my work researching parsing differentials. I would be happy to open a PR, but I am not quite sure to what degree you want to include additional sanitizers.

Sanitizers in question are for example [Typo3 html-sanitizer](https://github.com/TYPO3/html-sanitizer/), [OWASP Antisamy (Java/.NET)](https://github.com/nahsra/antisamy), [rgrove/sanitize](https://github.com/rgrove/sanitize), and some more.

Cheers,
leeN

**Comment by Yaniv-git** [comment]
Hi @leeN,

Thanks for the feedback and willingness to contribute!
Our intention for the example page is to focus more on showcasing different techniques of bypasses rather than a variety of sanitizers. If you have some examples that you think demonstrate other mXSS fundamentals/ideas than what is already presented, regardless of the sanitizer, feel free to send a pull request :)

Best,
Yaniv
